### ISSUE TITLE
No way to turn off

### ISSUE THREAD

**Issue by Lewiscowles1986** [raspberrypi/pix-plym-splash#1]
So this happened...

https://twitter.com/cymplecy/status/781124489287442432

I've written a basic script that turns off the boot splash, and modified the same script so it can turn it on again.

**turn off**  
```
sudo sed -i.bak '/boot/cmdline.txt' -e 's/ splash / nosplash /'
```

**turn on**  
```
sudo sed -i.bak '/boot/cmdline.txt' -e 's/ nosplash / splash /'
```

I'd love it if this could be worked into a script (I'd happily contribute this), but alternatively feel free to mark as wontfix, and I can link in forums so people can find how to easily turn off splash (no Idea why anyone would, in the 90's boot splash was one of the things I used to have to manually build into linux).

**Comment by spl237** [comment]
I'm waiting to see what the reaction from the community is to the lack of boot text before I make any decision about this. If it is felt by a sufficiently large number of people that the boot text is a worthwhile thing to have, I will add it as an option to the Raspberry Pi Configuration application (which already includes code to enable and disable it, as it is turned off when booting to CLI - the "proper" way of doing so is to remove the "quiet splash" parameters from the command line).

For what it's worth, to me, the boot text is hugely dated in appearance, and mostly useless with the speed of the parallel boot processes under systemd, not to mention meaningless to the vast majority of Pi users even if it was slow enough to read. A splash screen is far more approachable and more in line with user expectations of a modern OS.

**Comment by Lewiscowles1986** [comment]
No need to re-open, but...

https://twitter.com/NoSheds/status/781412875894157314

**Comment by ghollingworth** [comment]
http://hackertyper.net/

Seems appropriate
